# Defines command-line arguments and dispatches pipeline subcommands.

import argparse
import sys
from pathlib import Path

from .common import PipelineError
from .workflow import build, prepare, refresh_workspace


def refresh(args):
    workspace = Path(args.workspace).expanduser().resolve()
    refresh_workspace(workspace)


def build_parser():
    parser = argparse.ArgumentParser(
        description="Build a traceable database business-standard catalog",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    prepare_parser = subparsers.add_parser(
        "prepare", help="Extract inputs and create an AI review workspace"
    )
    prepare_parser.add_argument(
        "--schema",
        action="append",
        default=[],
        help="DDL, SQLite database, or field inventory; repeatable",
    )
    prepare_parser.add_argument(
        "--standard",
        action="append",
        default=[],
        help="PDF or structured standard inventory; repeatable",
    )
    prepare_parser.add_argument(
        "--rules",
        action="append",
        default=[],
        help="User-defined rules; repeatable",
    )
    prepare_parser.add_argument(
        "--database-url-env",
        help="Name of the environment variable containing the SQLAlchemy URL; its value is not recorded",
    )
    prepare_parser.add_argument("--out-dir", required=True, help="Intermediate workspace directory")
    prepare_parser.add_argument(
        "--top-k", type=int, default=5, help="Standard candidates per field; default: 5"
    )
    prepare_parser.set_defaults(func=prepare)

    refresh_parser = subparsers.add_parser(
        "refresh", help="Merge AI-reviewed standards and recalculate match candidates"
    )
    refresh_parser.add_argument(
        "--workspace", required=True, help="Workspace generated by prepare"
    )
    refresh_parser.set_defaults(func=refresh)

    build_parser_command = subparsers.add_parser(
        "build", help="Validate AI decisions and write Excel, CSV, and JSONL outputs"
    )
    build_parser_command.add_argument(
        "--workspace", required=True, help="Workspace generated by prepare"
    )
    build_parser_command.add_argument("--output", required=True, help="Output .xlsx file")
    build_parser_command.add_argument(
        "--allow-incomplete",
        action="store_true",
        help="Allow uncovered fields; use only for an explicitly requested draft",
    )
    build_parser_command.set_defaults(func=build)
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if getattr(args, "top_k", 1) < 1:
            raise PipelineError("--top-k must be greater than 0")
        args.func(args)
    except PipelineError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    return 0
